services:
  palworld-dedicated:
    build: ./bullseye
    container_name: palworld-dedicated
    restart: unless-stopped
    volumes:
      - gamedata:/home/steam/palworld-dedicated
      - backupdata:/home/steam/palworld-dedicated-backup
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    expose:
      - "25575/tcp"
    environment:
      - MAXPLAYERS=10
      - SERVER_PASSWORD_FILE=/run/secrets/server_password
      - ADMIN_PASSWORD_FILE=/run/secrets/admin_password
      - SERVER_NAME="Private Dedicated Server"
      - SERVER_DESCRIPTION="Private Server"

secrets:
  server_password:
    file: ./server_password.txt
  admin_password:
    file: ./admin_password.txt

volumes:
  gamedata:
  backupdata:
