services:
  palworld:
    build: ./bullseye
    restart: unless-stopped
    volumes:
      - gamedata:/home/steam/palworld-dedicated
    network_mode: "host"
    environment:
      - PORT=8211
      - QUERY_PORT=27015
      - RCON_PORT=25575
      - MAXPLAYERS=10
      - SERVER_PASSWORD=""
      - ADMIN_PASSWORD="chageme"
      - SERVER_NAME="Private Dedicated Server"
      - SERVER_DESCRIPTION="Private Server"

volumes:
  gamedata:
