services:
  palworld-dedicated:
    build: ./bullseye
    container_name: palworld-dedicated
    restart: unless-stopped
    volumes:
      - gamedata:/home/steam/palworld-dedicated
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    expose:
      - "25575/tcp"
    environment:
      - PORT=8211
      - QUERY_PORT=27015
      - RCON_PORT=25575
      - MAXPLAYERS=10
      - SERVER_PASSWORD=""
      - ADMIN_PASSWORD="chageme"
      - SERVER_NAME="Private Dedicated Server"
      - SERVER_DESCRIPTION="Private Server"

volumes:
  gamedata:
