services:
  game:
    build: ./bullseye
    container_name: palworld-dedicated
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - gamedata:/home/steam/palworld-dedicated
      - backupdata:/home/steam/palworld-dedicated-backup
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    expose:
      - "25575/tcp"
    environment:
      - MAXPLAYERS=10
      - SERVER_PASSWORD_FILE=/run/secrets/server_password
      - ADMIN_PASSWORD_FILE=/run/secrets/admin_password
      - SERVER_NAME="Palworld Dedicated Server"
      - SERVER_DESCRIPTION="Dedicated Server"

networks:
   default:
     enable_ipv6: true
     ipam:
       config:
         - subnet: 172.18.0.0/16
         - subnet: fd3b:7145:299:0:172:18::/16

secrets:
  server_password:
    file: ./server_password.txt
  admin_password:
    file: ./admin_password.txt

volumes:
  gamedata:
  backupdata:
